import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../components/navbar";
import { Col, Row } from "@nextui-org/react";
import { Directory } from "../components/Directory";
import { Messages } from "../components/Messages";
import { Chat } from "../components/Chat";
import { getAuth, User } from 'firebase/auth';
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { PulseLoader } from 'react-spinners';

const Home: NextPage = () => {
    const auth = getAuth();
    const [loading, setLoading] = useState(true);
    const router = useRouter();
    const user = auth.currentUser;
    useEffect(() => {
        console.log(auth.currentUser);
        if (!auth.currentUser) {
            router.push("/signup");
        } else {
            setLoading(false);
        }
    }, []);

    return (
        < div className={styles.container} >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {loading ? <div style={{ position: 'absolute', top: '50%', left: '50%' }} >
                    <PulseLoader size={80} color="#4443FF" />
                </div> :
                    <Row style={{ height: "100vh" }} justify="center" align="flex-start">
                        <Navbar photo={user?.photoURL == null ? " " : user.photoURL} />
                        <Messages user={user} />
                        <Chat />
                        <Directory />
                    </Row>
                }
            </main>
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div >
    );
};

export default Home;
