import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../components/navbar";
import { Col, Row } from "@nextui-org/react";
import { Directory } from "../components/Directory";
import { Messages } from "../components/Messages";
import { Chat } from "../components/Chat";
import { getAuth, User } from 'firebase/auth';
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
const Home: NextPage = () => {
    const auth = getAuth();
    const router = useRouter();
    const user = auth.currentUser;
    useEffect(() => {
        console.log(auth.currentUser);
        if (!auth.currentUser) {
            router.push("/signup");
        }
    }, []);

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Row style={{ height: "100vh" }} justify="center" align="flex-start">
                    <Navbar />
                    <Messages user={user} />
                    <Chat />
                    <Directory />
                </Row>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
};

export default Home;
